- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]

    #- set_fact:
    #    analyzers: "{% for i in groups['analyzers'] %}{% if skydive_nic is defined %}{{ hostvars[i][skydive_nic].ipv4.address }}{% else %}{{ hostvars[i].ansible_default_ipv4.address }}{% endif %}:8082{% if not loop.last %},{% endif %}{% endfor %}"
    #
- include: binary.yml
  when: skydive_deployment_mode == "binary"

- include: package.yml
  when: skydive_deployment_mode == "package"

- include: config.yml
