---
- name: Configure Mongo
  hosts: all
  gather_facts: True
  tasks:
    - include_role:
        name: skydive_agent
      vars:
        skydive_deployment_mode: binary

    - include_role:
        name: mongodb
      delegate_to: mongodb-1
      run_once: True

    - include_role:
        name: nodejs
      delegate_to: nodejs-1
      run_once: True
