---
- name: Install node
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - npm
    - git

- name: Clone repo
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_path }}"

- name: npm install
  command: "npm install"
  args:
    chdir: "{{ app_path }}"

- name: Create config
  template:
    src: nodejs.j2
    dest: /etc/sysconfig/nodejs
    mode: 0664

- name: Create systemd unit
  template:
    src: nodejs.service.j2
    dest: /etc/systemd/system/nodejs.service
    mode: 0664

- name: Reload
  systemd:
    daemon_reload: True
    name: nodejs
    state: started
