---
- name: Install
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - mongodb-server
    - python3-pymongo

- name: listen on all interfaces
  lineinfile:
    path: /etc/mongod.conf
    regexp: "^(.*)bindIp:(.*)$"
    line: "  bindIp: 0.0.0.0"
    backup: yes

- name: Start and enable mongodb
  systemd:
    name: mongod
    state: started
    enabled: True

- name: Create Admin account
  mongodb_user:
    database: admin
    name: admin
    password: admin
    roles:
      - userAdminAnyDatabase

- name: Create database and user
  mongodb_user:
    database: "{{ database }}"
    name: "{{ username }}"
    password: "{{ password }}"
    login_user: admin
    login_password: admin
    state: present
